version: '2'
services:
    cblog-app:
        image: cblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cblog-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    cblog-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: cblog-cassandra
    cblog-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=cblog-cassandra
    cblog-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: cblog-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
